### ISSUE TITLE
Support higher ruby versions

### ISSUE THREAD

**Issue by ahmgeek** [runtastic/rt_rubocop_defaults#8]
Hey @andreaseger 😘
Can you drop the dependency on ruby versions?
something like `sepc.required_ruby_version = '>= 2.0.0'`  would be much better.

**Comment by andreaseger** [comment]
hey @ahmgeek 
not sure I understand you correctly but I don't think allowing 2.0.0 makes much sense to be honest.
- latest rubocop itself doesn't work for such old ruby versions see the [support matrix](https://docs.rubocop.org/rubocop/compatibility.html#support-matrix).
- current master (and v1.2.4) assumes at least ruby 2.3 in the [config](https://github.com/runtastic/rt_rubocop_defaults/blob/master/config/default.yml#L6) and the latest rubocop for 2.3 (with the fix from #6 we also set the last rubocop version that supports 2.3 correctly)

Also we'll bump this in #7 to 2.4 both in the the config and gemspec

We also only set the lower version (now `~> 2.3` soon `~> 2.4`) and that will work for everything up to ruby 3 and when that comes we'll have to see anyway if changes are needed.

**Comment by ahmgeek** [comment]
oh, then it's my bad I though this is where the error stems.
but I think it's from here: 
https://github.com/runtastic/rt_rubocop_defaults/blob/2d7e414441aadfeef5838e050a8c210204387ff3/config/default.yml#L6

I overrode it in my `rubocop.yml` and it worked fine.
The error was: 
`RuboCop found unknown Ruby version: 2.3`

Thanks Andy

**Comment by andreaseger** [comment]
yeah might have been a rubocop version that's newer then 0.79 then you get this error. #6 will be the last release for 2.3 and lock rubocop to that exact version. #7 will then update everything to a minimum of 2.4 and rubocop v0.88

**Comment by andreaseger** [comment]
@ahmgeek FYI 1.3.0 released now with all new cops configured/enabled and min version set to 2.4

**Comment by ahmgeek** [comment]
@andreaseger thanks buddy
